#!/usr/bin/env zsh
# startup -- start several programs after x server initializes, based on hostname

# only execute for magenta
if [[ $HOST == "magenta" ]]; then
    xbacklight -set 30
    runsvdir -P ~/.sv/service &

elif [[ $HOST == "turquoise" ]]; then
	(sleep 2 && runsvdir -P ~/.sv/service) &

elif [[ $HOST == "gamagoori" ]]; then
    /usr/lib/libexec/kdeconnectd &
    /usr/bin/pipewire &
    /usr/bin/pipewire-pulse &
    /usr/bin/pipewire-media-session &
    dwmblocks &
    backg &
    mstart
elif [[ $HOST == "barazo" ]]; then
    # TODO: fix this
    dwmblocks &
    backg &
    startup
fi
